---

- ros_topic_name: "/crystal/arm_base"
  gz_topic_name: "/model/hb_crystal/joint/arm_base/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/glacio/arm_base"
  gz_topic_name: "/model/hb_glacio/joint/arm_base/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/frostbite/arm_base"
  gz_topic_name: "/model/hb_frostbite/joint/arm_base/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/crystal/arm_elbow"
  gz_topic_name: "/model/hb_crystal/joint/arm_elbow/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/glacio/arm_elbow"
  gz_topic_name: "/model/hb_glacio/joint/arm_elbow/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/frostbite/arm_elbow"
  gz_topic_name: "/model/hb_frostbite/joint/arm_elbow/cmd_vel"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "ignition.msgs.Double"
  direction: ROS_TO_GZ

- ros_topic_name: "/crystal/joint_states"
  gz_topic_name: "/world/default/model/hb_crystal/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/frostbite/joint_states"
  gz_topic_name: "/world/default/model/hb_frostbite/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/glacio/joint_states"
  gz_topic_name: "/world/default/model/hb_glacio/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera_sensor"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- ros_topic_name: "_hb_crystal/cmd_vel"
  gz_topic_name: "/model/hb_crystal/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "_hb_glacio/cmd_vel"
  gz_topic_name: "/model/hb_glacio/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ

- ros_topic_name: "_hb_frostbite/cmd_vel"
  gz_topic_name: "/model/hb_frostbite/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "ignition.msgs.Twist"
  direction: ROS_TO_GZ